/* eslint-disable */
// @ts-nocheck

/**
 * !The content of the file generated by the template content, if necessary, please refer to the use of custom templates:https://www.npmjs.com/package/swagger2apis#%E5%85%B3%E4%BA%8E%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E8%87%AA%E5%B7%B1%E7%9A%84%E6%A8%A1%E6%9D%BF
 *
 */
import { adaptorFn } from "../request.ts"
      
/**
 * @description: pet: Addanewpettothestore
 */
export const PetPOST = (
      parameter : BASE.IPet     = {} as any,
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/pet`,
    method: "POST",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: Addanewpettothestore',
        apiName:'PetPOST'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: pet: Updateanexistingpet
 */
export const PetPUT = (
      parameter : BASE.IPet     = {} as any,
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/pet`,
    method: "PUT",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: Updateanexistingpet',
        apiName:'PetPUT'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: pet: Multiplestatusvaluescanbeprovidedwithcommaseparatedstrings
 */
export const Pet_FindByStatusGET = (
      parameter : {status: array}     = {} as any,
    ...args:any
): Promise<BASE.IPet[]> => {
  const handledData = {
    url: `/pet/findByStatus`,
    method: "GET",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: Multiplestatusvaluescanbeprovidedwithcommaseparatedstrings',
        apiName:'Pet_FindByStatusGET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: pet: Mulipletagscanbeprovidedwithcommaseparatedstrings.Usetag1,tag2,tag3fortesting.
 */
export const Pet_FindByTagsGET = (
      parameter : {tags: array}     = {} as any,
    ...args:any
): Promise<BASE.IPet[]> => {
  const handledData = {
    url: `/pet/findByTags`,
    method: "GET",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: Mulipletagscanbeprovidedwithcommaseparatedstrings.Usetag1,tag2,tag3fortesting.',
        apiName:'Pet_FindByTagsGET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: pet: Returnsasinglepet
 */
export const Pet_PetId_$petId$GET = (
      parameter : string     = '',
    ...args:any
): Promise<BASE.IPet> => {
  const handledData = {
    url: `/pet/${parameter}`,
    method: "GET",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: Returnsasinglepet',
        apiName:'Pet_PetId_$petId$GET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: pet: Updatesapetinthestorewithformdata
 */
export const Pet_PetId_$petId$POST = (
      parameter : string     = '',
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/pet/${parameter}`,
    method: "POST",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: Updatesapetinthestorewithformdata',
        apiName:'Pet_PetId_$petId$POST'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: pet: Deletesapet
 */
export const Pet_PetId_$petId$DELETE = (
      parameter : string     = '',
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/pet/${parameter}`,
    method: "DELETE",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: Deletesapet',
        apiName:'Pet_PetId_$petId$DELETE'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: pet: uploadsanimage
 */
export const Pet_PetId_UploadImage_$petId$POST = (
      parameter : string     = '',
    ...args:any
): Promise<BASE.IApiResponse> => {
  const handledData = {
    url: `/pet/${parameter}/uploadImage`,
    method: "POST",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'pet: uploadsanimage',
        apiName:'Pet_PetId_UploadImage_$petId$POST'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: store: Returnsamapofstatuscodestoquantities
 */
export const Store_InventoryGET = (
    ...args:any
): Promise<object> => {
  const handledData = {
    url: `/store/inventory`,
    method: "GET",
              bonusInfo:{
        namespace:'BASE',
        description:'store: Returnsamapofstatuscodestoquantities',
        apiName:'Store_InventoryGET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: store: Placeanorderforapet
 */
export const Store_OrderPOST = (
      parameter : BASE.IOrder     = {} as any,
    ...args:any
): Promise<BASE.IOrder> => {
  const handledData = {
    url: `/store/order`,
    method: "POST",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'store: Placeanorderforapet',
        apiName:'Store_OrderPOST'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: store: ForvalidresponsetryintegerIDswithvalue>=1and<=10.Othervalueswillgeneratedexceptions
 */
export const Store_Order_OrderId_$orderId$GET = (
      parameter : string     = '',
    ...args:any
): Promise<BASE.IOrder> => {
  const handledData = {
    url: `/store/order/${parameter}`,
    method: "GET",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'store: ForvalidresponsetryintegerIDswithvalue&gt;=1and&lt;=10.Othervalueswillgeneratedexceptions',
        apiName:'Store_Order_OrderId_$orderId$GET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: store: ForvalidresponsetryintegerIDswithpositiveintegervalue.Negativeornon-integervalueswillgenerateAPIerrors
 */
export const Store_Order_OrderId_$orderId$DELETE = (
      parameter : string     = '',
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/store/order/${parameter}`,
    method: "DELETE",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'store: ForvalidresponsetryintegerIDswithpositiveintegervalue.Negativeornon-integervalueswillgenerateAPIerrors',
        apiName:'Store_Order_OrderId_$orderId$DELETE'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Thiscanonlybedonebytheloggedinuser.
 */
export const UserPOST = (
      parameter : BASE.IUser     = {} as any,
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/user`,
    method: "POST",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'user: Thiscanonlybedonebytheloggedinuser.',
        apiName:'UserPOST'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Createslistofuserswithgiveninputarray
 */
export const User_CreateWithArrayPOST = (
      parameter : BASE.IUser[]     = {} as any,
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/user/createWithArray`,
    method: "POST",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'user: Createslistofuserswithgiveninputarray',
        apiName:'User_CreateWithArrayPOST'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Createslistofuserswithgiveninputarray
 */
export const User_CreateWithListPOST = (
      parameter : BASE.IUser[]     = {} as any,
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/user/createWithList`,
    method: "POST",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'user: Createslistofuserswithgiveninputarray',
        apiName:'User_CreateWithListPOST'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Logsuserintothesystem
 */
export const User_LoginGET = (
      parameter : {username: string,password: string}     = {} as any,
    ...args:any
): Promise<string> => {
  const handledData = {
    url: `/user/login`,
    method: "GET",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'user: Logsuserintothesystem',
        apiName:'User_LoginGET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Logsoutcurrentloggedinusersession
 */
export const User_LogoutGET = (
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/user/logout`,
    method: "GET",
              bonusInfo:{
        namespace:'BASE',
        description:'user: Logsoutcurrentloggedinusersession',
        apiName:'User_LogoutGET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Getuserbyusername
 */
export const User_Username_$username$GET = (
      parameter : string     = '',
    ...args:any
): Promise<BASE.IUser> => {
  const handledData = {
    url: `/user/${parameter}`,
    method: "GET",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'user: Getuserbyusername',
        apiName:'User_Username_$username$GET'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Thiscanonlybedonebytheloggedinuser.
 */
export const User_Username_$username$PUT = (
      parameter : string     = '',
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/user/${parameter}`,
    method: "PUT",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'user: Thiscanonlybedonebytheloggedinuser.',
        apiName:'User_Username_$username$PUT'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}

/**
 * @description: user: Thiscanonlybedonebytheloggedinuser.
 */
export const User_Username_$username$DELETE = (
      parameter : string     = '',
    ...args:any
): Promise<any> => {
  const handledData = {
    url: `/user/${parameter}`,
    method: "DELETE",
        parameter,
              bonusInfo:{
        namespace:'BASE',
        description:'user: Thiscanonlybedonebytheloggedinuser.',
        apiName:'User_Username_$username$DELETE'
      }
      }
  const responese = adaptorFn(handledData, ...args);
  return responese;
}
